[package]
name = "feedcruncher"
version = "0.1.0"
authors = ["Michael Schubert <schu@schu.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.1"
reqwest = { version = "0.10", features = ["blocking"] }
rss = "1.9"
