[package]
name = "feedcruncher"
version = "0.1.0"
authors = ["Michael Schubert <schu@schu.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
